### PR TITLE
added soft wrap to removed diff editor

### PR DESCRIPTION
**Pull request by alpianon**
solves issue #8

### CODE REVIEW

**Comment by alpianon** [comment]
solves also issue #10

**Comment by t9md** [comment]
Thanks maybe this PR is OK for the quality, but please separate PRs otherwise checking it would be very tedious.

**Comment by t9md** [comment]
Never mind, I can check, since there is just TWO separate commit.

**Comment by t9md** [comment]
OK, 2nd PR is tough to check
- I want you to separate into TWO PRs, 1st one for softwrap is immediatelyy mergable.
- 2nd one for DIFF accuracy, first separate PR, and I need some elabolation(plese do it AFTER separate PR). Since I remember I intentionally simplifiied diff algorithm when I folked Sam's one to avoid some caviat, your PR comment refferening Sam's code that make me feel worry to revert back to some unwanted behavior I've overcome.

**Comment by t9md** [comment]
https://github.com/samu/git-diff-details/issues/75

**Comment by alpianon** [comment]
Ok you're right.
I will make a new PR only for the softwrap thing and test more the code to highlight single words before submitting a new PR (if you are able to recall which was the unwanted behavior you got with Sam's code, I may try to fix it)

**Pull request closed without merging**
